title: Github Docs
description: A Jekyll theme for Github styled documentation
url: https://boycce.github.io
baseurl: "/github-docs"
githuburl: "https://github.com/boycce/github-docs"

author:
  name: 'Ricky Boyce'
  url:  https://rickyboyce.com

# Aux links for the naviation
aux_links:
  "Github docs on GitHub":
    - "//github.com/boycce/github-docs"

# https://pages.github.com/versions/
plugins:
  - jekyll-seo-tag

sass:
  style: :compressed

# Custom vars
# logo: "/assets/images/just-the-docs.png"
# ga_tracking: UA-2709176-10
