title: Github Docs
description: A Jekyll theme for Github styled documentation
github_url: "https://github.com/boycce/github-docs"
basedir: ""
favicon: "/assets/imgs/favicon.ico"

author:
  name: 'Ricky Boyce'
  url:  https://rickyboyce.com

# Aux links for the naviation
aux_links:
  "Github docs on GitHub":
    - "https://github.com/boycce/github-docs"

plugins:
  - jekyll-seo-tag

sass:
  style: :compressed

# Custom vars
# logo: "/assets/imgs/logo.png"
# ga_tracking: UA-2709176-10
